services:
  # Old environment
  web-old:
    image: nginx:1.27-alpine-slim
    configs:
      - source: old_conf
        target: /etc/nginx/conf.d/default.conf
      - source: old_index
        target: /var/www/html/index.html
    deploy:
      replicas: 2
      placement:
        constraints:
          - "node.role == worker"
    networks:
      - canary_net

  # New environment
  web-new:
    image: nginx:1.27-alpine-slim
    configs:
      - source: new_conf
        target: /etc/nginx/conf.d/default.conf
      - source: new_index
        target: /var/www/html/index.html
    deploy:
      replicas: 2
      placement:
        constraints:
          - "node.role == worker"
    networks:
      - canary_net

  # NGINX load balancer
  loadbalancer:
    image: nginx:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role == manager"
    ports:
      - "8484:80"
    configs:
      - source: loadbalancer_conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - canary_net
    depends_on:
      - old-app
      - new-app

configs:
  old_conf:
    file: ./nginx/old/conf.d/default.conf
  old_index:
    file: ./nginx/old/html/index.html
  new_conf:
    file: ./nginx/new/conf.d/default.conf
  new_index:
    file: ./nginx/new/html/index.html
  loadbalancer_conf:
    name: default-${SETTINGS_TIMESTAMP}.conf
    file: ./nginx/loadbalancer/conf.d/default.conf

networks:
  canary_net:
    driver: overlay
